# Generated by Django 5.2 on 2025-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otchestvo',
            field=models.TextField(default='', verbose_name='Отчество'),
        ),
    ]
