# Generated by Django 5.2 on 2025-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='car_image', verbose_name='Изображение'),
        ),
    ]
