# Generated by Django 5.2 on 2025-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='descriptio',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
