# Generated by Django 5.2 on 2025-04-30 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_descriptio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки заявки')),
                ('bid_address', models.TextField(verbose_name='Адрес заявки')),
                ('date_rent', models.TextField(verbose_name='Даты и сроки аренды')),
                ('cars', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
                'db_table': 'car_bid',
            },
        ),
    ]
