# Generated by Django 5.2 on 2025-05-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carsbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='descriptio',
        ),
    ]
