# Generated by Django 5.2 on 2025-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_cars_descriptio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Цена'),
        ),
    ]
