# Generated by Django 5.2 on 2025-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('what_likes', models.TextField(verbose_name='Что понравилось')),
                ('what_modern', models.TextField(verbose_name='Что можно улучшить')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
    ]
