# Generated by Django 5.2 on 2025-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categories_description_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='', upload_to='category_image', verbose_name='Изображение'),
        ),
    ]
